<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1KRAo2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1KRAo2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY1KRAo2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY1KRAo2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY1KRAo2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y1KRAo2',
    'container.build_id' => '4439a815',
    'container.build_time' => 1710949274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1KRAo2');
